version: '3.8'

services:

  redis:
    image: redis/redis-stack:latest
    container_name: redis_higher_lower
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    env_file:
      - .env
    restart: always

  flask-app:
    build: .
    container_name: flask_higher_lower
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    restart: on-failure

