version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      FLASK_SECRET_KEY: "${FLASK_SECRET_KEY}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
    depends_on:
      - redis
    volumes:
      - .:/app
    command: python app.py

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
