version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
    restart: always

  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    restart: on-failure
